# Generated by Django 5.2.9 on 2025-12-09 05:00

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_image_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='post_images/%Y/%m/%d/'),
        ),
    ]
